name: PR

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  checks:
    uses: palasthotel/github-workflows/.github/workflows/wp-plugin-pr.yml@v1
    with:
      slug: term-pages
      dev-plugin-name: Term Pages - DEV
      required-files: |
        admin.js
        languages/term-pages.pot
        languages/term-pages-de_DE.mo
